#!/bin/sh
# Start the fsync'd soak telemetry sampler (must run unattended from boot).

DAEMON=/usr/bin/soak-logger
PIDFILE=/var/run/soak-logger.pid

case "$1" in
  start)
	printf "Starting soak-logger: "
	start-stop-daemon -S -b -q -m -p $PIDFILE -x $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping soak-logger: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
